### ISSUE TITLE
Travis CI Builds

### ISSUE THREAD

**Issue by Perseverance** [MusalaSoft/atmosphere-docs#19]

**Comment by dim4o** [comment]
- [x] atmosphere-agent-device-lib
- [x] atmosphere-bitmap-comparison
- [x] atmosphere-client
- [x] atmosphere-client-server-lib
- [x]  atmosphere-commons
- [x] atmosphere-ime
- [x] atmosphere-server
- [x] atmosphere-server-agent-lib
- [x] atmosphere-service
- [x] atmosphere-agent
- [x] atmosphere-uiautomator-bridge
